# 服务端口号
server:
port: 8080
# 数据库地址
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hxbx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = UCT

    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.xpu.test.bean
  #告诉系统在哪里去找mapper.xml文件（映射文件
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.xpu.test.bean: debug
